# Generated by Django 5.2.1 on 2025-06-02 11:04

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
