# Generated by Django 5.2.1 on 2025-06-03 00:09

import service.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/prof_images/', validators=[service.validators.validate_file_size]),
        ),
    ]
