# Generated by Django 5.2.1 on 2025-06-01 16:13

import service.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[service.validators.validate_file_size]),
        ),
    ]
