# Generated by Django 5.2.1 on 2025-06-02 10:54

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_review_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
