# Generated by Django 5.2.1 on 2025-05-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='price_per_piece',
        ),
    ]
